### ISSUE TITLE
使用 RSS 减轻维护负担

### ISSUE THREAD

**Issue by frostming** [Zheaoli/cool-weekly#5]
首先感谢这个周报的集结 REPO ，只是感觉依靠手动编辑或接受 PR 来维护、更新周报索引会渐渐造成比较大的负担。
有没有可能换用更加自动化的方式，设想如下：

- 包含一个 JSON （或其他喜欢的配置格式）元数据文件，包含所有周报站点及其 RSS feed URL
- 创建 GitHub Action workflow 自动从元数据生成 OPML，这个OPML可以直接用RSS阅读器订阅收藏
- 如果要保留静态站点，可以在这基础上生成（但我认为其实上面就足够了）
- 当然，这里有个前提是周报需要支持RSS feed

**Comment by Zheaoli** [comment]
实际上有个问题在于，有些站点的周报没法放在 RSS 的更新范围内，，所以才有了这个汇总收藏的 Repo

不过好像也不是不能解，我想下怎么搞

**Comment by zdyxry** [comment]
有些周报本身是发布在博客上的，部分博客支持的 RSS 不支持过滤指定 tag，最终可能会演变成另一个独立博客收集站。

**Comment by frostming** [comment]
嗯，应该有别的办法，但不是RSS
